"""add summary of post

Revision ID: 9cec3bcf919b
Revises: c025b8fcfb9e
Create Date: 2017-11-10 15:37:45.971045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cec3bcf919b'
down_revision = 'c025b8fcfb9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('summary', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'summary')
    # ### end Alembic commands ###
